# ROLE cho ADMIN
api.v1.role.admin=ROLE_ADMIN

# ROLE cho USER
api.v1.role.user=ROLE_USER


# Phân quyền cho Orders API
api.v1.orders.create=ROLE_USER       # Tạo đơn hàng
api.v1.orders.view=ROLE_USER,ROLE_ADMIN    # Xem đơn hàng theo user_id
api.v1.orders.viewById=ROLE_USER,ROLE_ADMIN  # Xem chi tiết đơn hàng
api.v1.orders.update=ROLE_ADMIN      # Cập nhật đơn hàng
api.v1.orders.delete=ROLE_ADMIN      # Xóa đơn hàng
api.v1.orders.search=ROLE_ADMIN      # Tìm kiếm đơn hàng theo keyword


# Phân quyền cho Products API
api.v1.products.create=ROLE_ADMIN          # Tạo sản phẩm
api.v1.products.update=ROLE_ADMIN          # Cập nhật sản phẩm
api.v1.products.delete=ROLE_ADMIN          # Xóa sản phẩm
api.v1.products.view=PUBLIC                # Xem sản phẩm
api.v1.products.uploadImages=ROLE_ADMIN    # Upload ảnh sản phẩm
api.v1.products.export=ROLE_ADMIN          # Xuất log Excel
api.v1.products.search=PUBLIC              # Tìm kiếm sản phẩm
api.v1.products.byIds=PUBLIC               # Xem danh sách sản phẩm theo ID
api.v1.products.generateFake=ROLE_ADMIN    # Tạo dữ liệu giả
api.v1.products.images=PUBLIC              # Xem ảnh sản phẩm



# Phân quyền cho Orders_Details API
api.v1.ordersDetails.create=ROLE_ADMIN          # Tạo chi tiết đơn hàng
api.v1.ordersDetails.view=ROLE_USER,ROLE_ADMIN  # Xem chi tiết đơn hàng
api.v1.ordersDetails.update=ROLE_ADMIN          # Cập nhật chi tiết đơn hàng
api.v1.ordersDetails.delete=ROLE_ADMIN          # Xóa chi tiết đơn hàng
api.v1.ordersDetails.viewByOrder=ROLE_USER,ROLE_ADMIN  # Xem chi tiết theo đơn hàng

# Phân quyền cho Categories API
api.v1.categories.create=ROLE_ADMIN          # Tạo danh mục mới
api.v1.categories.update=ROLE_ADMIN          # Cập nhật danh mục
api.v1.categories.delete=ROLE_ADMIN          # Xóa danh mục
api.v1.categories.view=ROLE_USER,ROLE_ADMIN  # Xem danh sách danh mục
api.v1.categories.search=ROLE_USER,ROLE_ADMIN # Tìm kiếm danh mục theo tên

api.v1.coupons.create=ROLE_ADMIN            # Tạo mã giảm giá
api.v1.coupons.update=ROLE_ADMIN            # Cập nhật mã giảm giá
api.v1.coupons.delete=ROLE_ADMIN            # Xóa mã giảm giá
api.v1.coupons.view=ROLE_USER,ROLE_ADMIN    # Xem mã giảm giá
api.v1.coupons.validate=ROLE_USER,ROLE_ADMIN # Xác thực mã giảm giá



# Phân quyền cho User APIs
api.v1.users.register=PERMIT_ALL             # Đăng ký tài khoản
api.v1.users.login=PERMIT_ALL                # Đăng nhập

api.v1.users.details=ROLE_USER,ROLE_ADMIN    # Xem chi tiết thông tin người dùng
api.v1.users.update-details=ROLE_USER        # Cập nhật thông tin người dùng
api.v1.users.me=ROLE_USER                    # Lấy thông tin người dùng hiện tại
api.v1.users.get=ROLE_ADMIN                  # Xem danh sách người dùng
api.v1.users.export=ROLE_ADMIN               # Xuất danh sách người dùng
api.v1.users.import=ROLE_ADMIN               # Import danh sách người dùng

# Phân quyền mặc định
api.v1.default.authenticated=AUTHENTICATED
